version: '3.5'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASS}
    ports:
      - '3306:3306'
    volumes:
      - walltracker-db:/var/lib/mysql
    networks:
      - walltracker-network

  walltracker-api:
    image: mrsteeltitan/walltracker:latest
    ports:
      - '8080:8080'
    networks:
      - walltracker-network

networks:
  walltracker-network:
    driver: bridge

volumes:
  walltracker-db:
